require "nokogiri"
require "open-uri"
require "pry"
require "colorize"
require "artii"

require_relative "tealish/version"
require_relative "tealish/cli"
require_relative "tealish/scraper"
require_relative "tealish/teas"
